### ISSUE TITLE
Error when formatting while no folder is open

### ISSUE THREAD

**Issue by alvv-z** [ziglang/sublime-zig-language#63]
When formatting a file without an open folder, Sublime Text 3211 and 4126 show an error in the console. I haven't tested this in other Versions.

Console Output:
```python
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 1456, in run_
    return self.run(**args)
  File "/home/$USER/.config/sublime-text-3/Installed Packages/Zig Language.sublime-package/Zig.py", line 149, in run
KeyError: 'folder'
```

**Comment by gnarz** [comment]
I have encountered the same issue. The problem is line 149 of Zig.py, which looks like this:
`  working_dir = vars.get('file_path', vars['folder'])`
I removed the `. vars['folder']` and it works again. This is probably not a proper fix, but this should be the place to fix it.

**Comment by jiacai2050** [comment]
@gwenzek Hi, do you think `working_dir = vars.get('file_path')` is a valid fix for this issue?
